[package]
name = "winrise-kernel"
version = "0.1.0"
edition = "2024"
description = "Kernel do WinRise OS"
license = "MIT"

[[bin]]
name = "kernel"
path = "src/main.rs"
test = false
bench = false

[dependencies]
limine = "0.6.5"
x86_64 = "0.15.5"
spin = "0.12.3"
noto-sans-mono-bitmap = { version = "0.3.2", default-features = false, features = [
    "regular", "bold", "size_16", "size_32",
    "unicode-basic-latin", "unicode-latin-1-supplement",
] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 2
debug = true
