#!/bin/sh
# Configuração do live-build do WinRise Connect OS (Debian 13 "trixie", amd64, UEFI + BIOS)
set -e
lb config noauto \
  --mode debian \
  --distribution trixie \
  --architecture amd64 \
  --archive-areas "main contrib non-free non-free-firmware" \
  --parent-archive-areas "main contrib non-free non-free-firmware" \
  --mirror-bootstrap "http://deb.debian.org/debian/" \
  --mirror-binary "http://deb.debian.org/debian/" \
  --mirror-chroot-security "http://deb.debian.org/debian-security/" \
  --mirror-binary-security "http://deb.debian.org/debian-security/" \
  --security true \
  --updates true \
  --linux-flavours amd64 \
  --apt-recommends true \
  --apt-options "--yes -o Acquire::Retries=10 -o Acquire::Retries::Delay::Maximum=30 -o Acquire::http::Pipeline-Depth=0" \
  --firmware-chroot true \
  --firmware-binary true \
  --debian-installer none \
  --binary-images iso-hybrid \
  --bootloaders "grub-efi,syslinux" \
  --memtest none \
  --image-name winrise-connect-os \
  --iso-application "WinRise Connect OS" \
  --iso-publisher "WinRise Connect OS - https://github.com/wglebioravel/winrise-connect-os" \
  --iso-volume "WINRISE_CONNECT" \
  --bootappend-live "boot=live components quiet locales=pt_BR.UTF-8 keyboard-layouts=br keyboard-model=abnt2 timezone=America/Sao_Paulo username=winrise user-fullname=WinRise hostname=winrise" \
  "${@}"
